<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.polarbookshop.catalogservice.domain.BookRepositoryJdbcTests" tests="7" skipped="0" failures="0" errors="0" timestamp="2024-07-12T13:27:12" hostname="MacBook-Pro-tilhrende-Nicklas.local" time="0.088">
  <properties/>
  <testcase name="findBookByIsbnWhenNotExisting()" classname="com.polarbookshop.catalogservice.domain.BookRepositoryJdbcTests" time="0.047"/>
  <testcase name="existsByIsbnWhenExisting()" classname="com.polarbookshop.catalogservice.domain.BookRepositoryJdbcTests" time="0.007"/>
  <testcase name="deleteByIsbn()" classname="com.polarbookshop.catalogservice.domain.BookRepositoryJdbcTests" time="0.006"/>
  <testcase name="findBookByIsbnWhenExisting()" classname="com.polarbookshop.catalogservice.domain.BookRepositoryJdbcTests" time="0.011"/>
  <testcase name="checkConfig()" classname="com.polarbookshop.catalogservice.domain.BookRepositoryJdbcTests" time="0.001"/>
  <testcase name="existsByIsbnWhenNotExisting()" classname="com.polarbookshop.catalogservice.domain.BookRepositoryJdbcTests" time="0.003"/>
  <testcase name="findAllBooks()" classname="com.polarbookshop.catalogservice.domain.BookRepositoryJdbcTests" time="0.011"/>
  <system-out><![CDATA[2024-07-12T15:27:12.298+02:00  INFO 5795 --- [catalog-service] [    Test worker] t.c.s.AnnotationConfigContextLoaderUtils : Could not detect default configuration classes for test class [com.polarbookshop.catalogservice.domain.BookRepositoryJdbcTests]: BookRepositoryJdbcTests does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
2024-07-12T15:27:12.306+02:00  INFO 5795 --- [catalog-service] [    Test worker] .b.t.c.SpringBootTestContextBootstrapper : Found @SpringBootConfiguration com.polarbookshop.catalogservice.CatalogServiceApplication for test class com.polarbookshop.catalogservice.domain.BookRepositoryJdbcTests

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.2.7)

2024-07-12T15:27:12.332+02:00  INFO 5795 --- [catalog-service] [    Test worker] c.p.c.domain.BookRepositoryJdbcTests     : Starting BookRepositoryJdbcTests using Java 17.0.3 with PID 5795 (started by nicklasroed in /Users/nicklasroed/Desktop/Spring Boot in Action/catalog-service)
2024-07-12T15:27:12.333+02:00  INFO 5795 --- [catalog-service] [    Test worker] c.p.c.domain.BookRepositoryJdbcTests     : The following 1 profile is active: "integration"
2024-07-12T15:27:12.333+02:00  INFO 5795 --- [catalog-service] [    Test worker] o.s.c.c.c.ConfigServerConfigDataLoader   : Fetching config from server at : http://localhost:8888
2024-07-12T15:27:12.333+02:00  INFO 5795 --- [catalog-service] [    Test worker] o.s.c.c.c.ConfigServerConfigDataLoader   : Exception on Url - http://localhost:8888:org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8888/catalog-service/default": Connection refused. Will be trying the next url if available
2024-07-12T15:27:12.333+02:00  WARN 5795 --- [catalog-service] [    Test worker] o.s.c.c.c.ConfigServerConfigDataLoader   : Could not locate PropertySource ([ConfigServerConfigDataResource@2b284acc uris = array<String>['http://localhost:8888'], optional = true, profiles = 'default']): I/O error on GET request for "http://localhost:8888/catalog-service/default": Connection refused
2024-07-12T15:27:12.333+02:00  INFO 5795 --- [catalog-service] [    Test worker] o.s.c.c.c.ConfigServerConfigDataLoader   : Fetching config from server at : http://localhost:8888
2024-07-12T15:27:12.333+02:00  INFO 5795 --- [catalog-service] [    Test worker] o.s.c.c.c.ConfigServerConfigDataLoader   : Exception on Url - http://localhost:8888:org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8888/catalog-service/integration": Connection refused. Will be trying the next url if available
2024-07-12T15:27:12.333+02:00  WARN 5795 --- [catalog-service] [    Test worker] o.s.c.c.c.ConfigServerConfigDataLoader   : Could not locate PropertySource ([ConfigServerConfigDataResource@76e5278a uris = array<String>['http://localhost:8888'], optional = true, profiles = 'integration']): I/O error on GET request for "http://localhost:8888/catalog-service/integration": Connection refused
2024-07-12T15:27:12.333+02:00  INFO 5795 --- [catalog-service] [    Test worker] o.s.c.c.c.ConfigServerConfigDataLoader   : Fetching config from server at : http://localhost:8888
2024-07-12T15:27:12.333+02:00  INFO 5795 --- [catalog-service] [    Test worker] o.s.c.c.c.ConfigServerConfigDataLoader   : Exception on Url - http://localhost:8888:org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8888/catalog-service/default": Connection refused. Will be trying the next url if available
2024-07-12T15:27:12.333+02:00  WARN 5795 --- [catalog-service] [    Test worker] o.s.c.c.c.ConfigServerConfigDataLoader   : Could not locate PropertySource ([ConfigServerConfigDataResource@70cc0601 uris = array<String>['http://localhost:8888'], optional = true, profiles = 'default']): I/O error on GET request for "http://localhost:8888/catalog-service/default": Connection refused
2024-07-12T15:27:12.387+02:00  INFO 5795 --- [catalog-service] [    Test worker] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JDBC repositories in DEFAULT mode.
2024-07-12T15:27:12.389+02:00  INFO 5795 --- [catalog-service] [    Test worker] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 2 ms. Found 1 JDBC repository interface.
2024-07-12T15:27:12.407+02:00  INFO 5795 --- [catalog-service] [    Test worker] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Starting...
2024-07-12T15:27:12.429+02:00  INFO 5795 --- [catalog-service] [    Test worker] com.zaxxer.hikari.pool.HikariPool        : HikariPool-2 - Added connection org.testcontainers.jdbc.ConnectionWrapper@52072c45
2024-07-12T15:27:12.429+02:00  INFO 5795 --- [catalog-service] [    Test worker] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Start completed.
2024-07-12T15:27:12.433+02:00  INFO 5795 --- [catalog-service] [    Test worker] org.flywaydb.core.FlywayExecutor         : Database: jdbc:postgresql://localhost:63257/test (PostgreSQL 14.12)
2024-07-12T15:27:12.442+02:00  INFO 5795 --- [catalog-service] [    Test worker] o.f.core.internal.command.DbValidate     : Successfully validated 2 migrations (execution time 00:00.004s)
2024-07-12T15:27:12.463+02:00  INFO 5795 --- [catalog-service] [    Test worker] o.f.core.internal.command.DbMigrate      : Current version of schema "public": 2
2024-07-12T15:27:12.463+02:00  INFO 5795 --- [catalog-service] [    Test worker] o.f.core.internal.command.DbMigrate      : Schema "public" is up to date. No migration necessary.
2024-07-12T15:27:12.498+02:00  INFO 5795 --- [catalog-service] [    Test worker] c.p.c.domain.BookRepositoryJdbcTests     : Started BookRepositoryJdbcTests in 0.19 seconds (process running for 5.719)
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
